[tool.poetry]
name = "cow-py"
version = "0.1.0"
description = ""
authors = ["José Ribeiro <jose@bleu.studio>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
httpx = "^0.26.0"
web3 = "^6.15.1"
pybars3 = "^0.9.7"
pydantic = "^2.6.2"


[tool.poetry.group.dev.dependencies]
ruff = "^0.2.2"
pyright ="^1.1.296"
pytest ="^7.2.1"
ipython = "*"
pre-commit = "3.*"
datamodel-code-generator = "^0.25.4"
ariadne-codegen = "^0.12.0"

[tool.poetry.scripts]
web3_codegen = 'cow_py.codegen.main:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ariadne-codegen]
remote_schema_url= "https://api.thegraph.com/subgraphs/name/cowprotocol/cow"
queries_path = "cow_py/subgraph/queries"
target_package_name="client"
target_package_path="cow_py/subgraph"
client_name="SubgraphClient"
client_file_name="subgraph_client"
